# Generated by Django 4.1.3 on 2023-07-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
