# Generated by Django 4.1.3 on 2023-08-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0002_remove_product_short_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Category',
        ),
    ]
